language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn test
after_success:
  - npx travis-deploy-once@5 "npx semantic-release@15"
branches:
  only:
    - master
